// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkhh7D_euVjosIKoExiAU6BqdTM8AHHQ',
    appId: '1:63210026230:web:931740c7ce240c6d5828d7',
    messagingSenderId: '63210026230',
    projectId: 'pisolocker',
    authDomain: 'pisolocker.firebaseapp.com',
    storageBucket: 'pisolocker.firebasestorage.app',
    measurementId: 'G-3JNJX0KEWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mCMlnW8QMiqLsw-qvUth2A9459CkpIo',
    appId: '1:63210026230:android:173b3f7b716be19a5828d7',
    messagingSenderId: '63210026230',
    projectId: 'pisolocker',
    storageBucket: 'pisolocker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDABYdMTNCEEEWwZP7mNqfKSiiBEwVAo',
    appId: '1:63210026230:ios:bc41ad4843102e195828d7',
    messagingSenderId: '63210026230',
    projectId: 'pisolocker',
    storageBucket: 'pisolocker.firebasestorage.app',
    iosBundleId: 'com.example.pisolocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkhh7D_euVjosIKoExiAU6BqdTM8AHHQ',
    appId: '1:63210026230:web:10da97033d54a99b5828d7',
    messagingSenderId: '63210026230',
    projectId: 'pisolocker',
    authDomain: 'pisolocker.firebaseapp.com',
    storageBucket: 'pisolocker.firebasestorage.app',
    measurementId: 'G-Y7ZCQTRSXM',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAYkhh7D_euVjosIKoExiAU6BqdTM8AHHQ',
    appId: '1:63210026230:web:10da97033d54a99b5828d7',
    messagingSenderId: '63210026230',
    projectId: 'pisolocker',
    authDomain: 'pisolocker.firebaseapp.com',
    storageBucket: 'pisolocker.firebasestorage.app',
    measurementId: 'G-Y7ZCQTRSXM',
  );
}
